#!/usr/bin/env python
import random
import os
import subprocess

# Change to where your wallpapers are located
WALLPAPER_SRC = "/home/YourUserName/backgrounds"
f = []
ext = [".jpg", ".jpeg", ".png"]
for file in os.listdir(WALLPAPER_SRC):
    if file.endswith(tuple(ext)):
        f.append(file)

total = len(f)
number = random.randint(1, total)
background = f[number]
new_wall = WALLPAPER_SRC + "/" + background

args = "DISPLAY=':0' feh --bg-fill %s" % new_wall
subprocess.Popen(args,shell=True)
